name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck cpplint valgrind

    - name: Сборка s21_cat
      run: make

    - name: Запуск s21_cat
      run: ./bin/s21_cat

    - name: Запуск cpplint
      run: make cpplint
      
    - name: Запуск cppcheck
      run: make cppcheck

    - name: Запуск valgrind
      run: make valgrind
